#!/usr/bin/env bash
# Transfers a file from our client to a server
if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	ssh -o StrictHostKeyChecking=no "$3@$2" 'exit'

	if [ -n "$4" ]; then
		scp -i "$4" "$1" "$3@$2:~/"
	else
		scp "$1" "$3@$2:~/"
	fi

	ssh -o StrictHostKeyChecking=yes "$3@$2" 'exit'
fi
