#!/usr/bin/env bash
# Installs nginx web server
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chown -R "$USER:$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html
service nginx restart
