#!/usr/bin/env bash
# Installs and configures Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER:$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/1337FIL permanent;" /etc/nginx/sites-enabled/default
sudo service nginx restart
