#!/usr/bin/env bash
# Installs and configures Nginx server so that /redirect_me is redirecting to another page.
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chown -R "$USER:$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html
sed -i "/root /var/www/html;/a rewrite ^/redirect_me https://www.youtube.com/watch? permanent;" /etc/nginx/sites-enabled/default
service nginx restart
