#!/usr/bin/env bash
# Installs and configure Nginx server to have a custom 404 page.
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chown -R "$USER:$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html
sed -i '/root /var/www/html;/a\\n\tlocation = /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/root /var/www/html;/a\\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-enabled/default
service nginx restart
