#!/usr/bin/env bash
# Installs and configure Nginx server to have a custom 404 page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER:$USER" /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "301 Moved Permanently" | sudo tee /var/www/html/redirect.html
sudo sed -i '/server_name _;/a\\nerror_page 301 /redirect.html;\n\tlocation = /redirect.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n\tlocation /redirect_me {\n\t\treturn 301 https://twitter.com/1337FIL;\n\t}' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '/server_name _;/a\\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo service nginx restart
