#!/usr/bin/env bash
# Installs and configure Nginx server to have a custom 404 page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER:$USER" /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/1337FIL permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/err_404.html > /dev/null
sudo sed -i '/listen 80 default_server;/a\\n\terror_page 404 /err_404.html;\n\tlocation = /err_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-enabled/default
sudo service nginx restart
