#!/usr/bin/env bash
# Installs and configure on lb-01 server
sudo apt-get -y update
sudo apt-get -y dist-upgrade
sudo apt-get -y install haproxy
sudo cp --backup=numbered /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo cp --backup=numbered /etc/default/haproxy /etc/default/haproxy.bak
sudo sed -i '$a\frontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\backend http_back\n\tbalance roundrobin\n\tserver 520327-web-01 52.86.133.238:80 check\n\tserver 520327-web-02 52.87.211.253:80 check' /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
