#!/usr/bin/env bash
# Installs and configure on lb-01 server
apt-get -y update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y update
apt-get -y install haproxy=2.8.\*
sed -i '$a\\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n' /etc/haproxy/haproxy.cfg
sed -i '$a\backend http_back\n\tbalance roundrobin\n\tserver 520327-web-01 52.86.133.238:80 check\n\tserver 520327-web-02 52.87.211.253:80 check' /etc/haproxy/haproxy.cfg
service haproxy restart
