#!/usr/bin/env bash
# Configures a server
apt-get -y update
apt-get -y install nginx
sed -i 's/^listen\s*\([0-9]*\)\s*;$/listen 80;/g' /etc/nginx/nginx.conf
ufw allow 'Nginx HTTP'
chown -R "$USER:$USER" /var/www/html
ln -s -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
