#!/usr/bin/env bash 
# This script displays the content of the file /etc/passwd (only username, user id and Home directory path for the user)

while read -r line
do
	echo "$line" | cut -d ':' -f1,3,6
done < "/etc/passwd"

