#!/usr/bin/env bash 
# This script displays the content of the file /etc/passwd

while IFS=: read -r username password uid gid user_info home_directory cmd_sh
do
    echo "The user $username is part of the $gid gang, lives in $home_directory and rides $cmd_sh. $uid's place is protected by the passcode $password, more info about the user here: $user_info"
done < "/etc/passwd"

